#!D:\portfolio projects details\Deep_Learning_Projects\Kidney_Disease_Classification_Deep_Learning\kidney_class_venv\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
